### ISSUE TITLE
Cant Use My Scraper Credentials : Scraping LImited - no credentials provided Error

### ISSUE THREAD

**Issue by 1n3tinct5** [gabrielfvale/scrappy#4]
Hi Gabriel,

love the work you have done on this scraper and it's really amazing just one thing bothers me and maybe it's a stupid question but, I am not able to use my Screenscraper credentials and get full access to unlimited downloads, maybe i am inputting them in on an incorrect file/place?

Would you mind telling me how i can do that so i don't get the Scraping Limited error?

I am using MuOs Banana.

Thank you in advance for the help, i appreciate it,

1n3tinct5

**Comment by gabrielfvale** [comment]
Hi, I appreciate your words and thank you for opening an issue. Please check the "Adding Credentials" section in the Wiki, make sure they are added to `skyscraper_config.ini`

https://github.com/gabrielfvale/scrappy/wiki/Configuration#adding-credentials
